{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Conexão\",\"ParametrosBase\",\"Arquivos\",\"Bandeiras\",\"Parametros\",\"Estados\",\"ApoiamentosMínimos\",\"DiasNaoUteis\",\"Dim_Estados\",\"Dim_Calendario\",\"Fato_Apoiamentos\",\"Coleta Aliança\",\"@Medidas\",\"Atualização\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.908.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Parametros",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = ParametrosBase,",
          "    #\"Linhas Filtradas1\" = Table.SelectRows(Fonte, each ([Extension] = \".xlsx\")),",
          "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Linhas Filtradas1\",{\"Content\"}),",
          "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Outras Colunas Removidas\", \"Dados\", each Excel.Workbook([Content])),",
          "    #\"Dados Expandido\" = Table.ExpandTableColumn(#\"Personalização Adicionada\", \"Dados\", {\"Name\", \"Data\", \"Item\", \"Kind\", \"Hidden\"}, {\"Name\", \"Data\", \"Item\", \"Kind\", \"Hidden\"}),",
          "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Dados Expandido\", each ([Kind] = \"Table\")),",
          "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Linhas Filtradas\",{\"Data\", \"Item\"})",
          "in",
          "    #\"Outras Colunas Removidas1\""
        ],
        "kind": "m",
        "lineageTag": "752fd049-5415-43bf-90e7-8353aa17d396",
        "queryGroup": "Parametros"
      },
      {
        "name": "Estados",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Parametros,",
          "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each ([Item] = \"Estados\")),",
          "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Linhas Filtradas\",{\"Data\"}),",
          "    #\"Data Expandido\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas\", \"Data\", {\"Região\", \"Nome\", \"Sigla\"}, {\"Região\", \"Nome\", \"Sigla\"}),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Data Expandido\",{{\"Região\", type text}, {\"Nome\", type text}, {\"Sigla\", type text}})",
          "in",
          "    #\"Tipo Alterado\""
        ],
        "kind": "m",
        "lineageTag": "ca5d52f1-6c38-4b46-b5ce-c16fc6613869",
        "queryGroup": "Parametros"
      },
      {
        "name": "ApoiamentosMínimos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Parametros,",
          "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each ([Item] = \"ApoiamentosMínimos\")),",
          "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Linhas Filtradas\",{\"Data\"}),",
          "    #\"Data Expandido\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas\", \"Data\", {\"UF\", \"VOTOS VALIDOS PARA CÂMARA DOS DEPUTADOS\", \"0,5% DOS VOTOS VALIDOS\", \"NÚMERO DO ELEITORADO QUE VOTOU\", \"0,1% DO ELEITORADO QUE VOTOU\"}, {\"UF\", \"VOTOS VALIDOS PARA CÂMARA DOS DEPUTADOS\", \"0,5% DOS VOTOS VALIDOS\", \"NÚMERO DO ELEITORADO QUE VOTOU\", \"0,1% DO ELEITORADO QUE VOTOU\"}),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Data Expandido\",{{\"UF\", type text}, {\"VOTOS VALIDOS PARA CÂMARA DOS DEPUTADOS\", type number}, {\"0,5% DOS VOTOS VALIDOS\", type number}, {\"NÚMERO DO ELEITORADO QUE VOTOU\", type number}, {\"0,1% DO ELEITORADO QUE VOTOU\", type number}})",
          "in",
          "    #\"Tipo Alterado\""
        ],
        "kind": "m",
        "lineageTag": "162e72ba-a20e-4fbf-bb03-4e8549505562",
        "queryGroup": "Parametros"
      },
      {
        "name": "DiasNaoUteis",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Parametros,",
          "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each ([Item] = \"DiasNaoUteis\")),",
          "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Linhas Filtradas\",{\"Data\"}),",
          "    #\"Data Expandido\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas\", \"Data\", {\"Datas\", \"Útil\"}, {\"Datas\", \"Útil\"}),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Data Expandido\",{{\"Datas\", type date}, {\"Útil\", type text}})",
          "in",
          "    #\"Tipo Alterado\""
        ],
        "kind": "m",
        "lineageTag": "7a36eb29-9c73-4fe7-9f7d-853d49fc9e4b",
        "queryGroup": "Parametros"
      },
      {
        "name": "Arquivos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Conexão,",
          "    Arquivos1 = Fonte{[Name=\"Arquivos\"]}[Content],",
          "    #\"Linhas Filtradas\" = Table.SelectRows(Arquivos1, each [Extension] = \".csv\")",
          "in",
          "    #\"Linhas Filtradas\""
        ],
        "kind": "m",
        "lineageTag": "1a2e592e-2f05-43b8-b3f9-adb965427431",
        "queryGroup": "ConexãoSharePoint"
      },
      {
        "name": "ParametrosBase",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Conexão,",
          "    Parametros1 = Fonte{[Name=\"Parametros\"]}[Content]",
          "in",
          "    Parametros1"
        ],
        "kind": "m",
        "lineageTag": "d3678087-b243-4edb-b75f-2a225e5c1984",
        "queryGroup": "ConexãoSharePoint"
      },
      {
        "name": "Conexão",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://eliasbarbosa0.sharepoint.com\", [ApiVersion = 15]),",
          "    #\"Documentos Compartilhados\" = Fonte{[Name=\"Documentos Compartilhados\"]}[Content],",
          "    #\"Validacao TSE\" = #\"Documentos Compartilhados\"{[Name=\"Validacao TSE\"]}[Content]",
          "in",
          "    #\"Validacao TSE\""
        ],
        "kind": "m",
        "lineageTag": "47b103b3-ff7c-442e-b65b-9514faf5b548",
        "queryGroup": "ConexãoSharePoint"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "ConexãoSharePoint"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Parametros"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Dimensões"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Fatos"
      }
    ],
    "relationships": [
      {
        "name": "643cb8d3-f1db-9403-8ca4-09bdc84ea843",
        "fromColumn": "Estado",
        "fromTable": "Fato_Apoiamentos",
        "toColumn": "Sigla",
        "toTable": "Dim_Estados"
      },
      {
        "name": "a0e4f59c-4fb6-cf9c-25cd-d27d3e8d30f1",
        "fromColumn": "Data",
        "fromTable": "Fato_Apoiamentos",
        "toColumn": "Data",
        "toTable": "Dim_Calendario"
      },
      {
        "name": "9badaf10-ddcc-a59c-6e0b-97db80bb5130",
        "fromColumn": "Data convetida",
        "fromTable": "Coleta Aliança",
        "toColumn": "Data",
        "toTable": "Dim_Calendario"
      },
      {
        "name": "3d1dcf5c-725f-4770-4142-71babc6eed06",
        "fromColumn": "Name",
        "fromTable": "Bandeiras",
        "toColumn": "Sigla",
        "toTable": "Dim_Estados"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Dim_Estados",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Região",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2caa878-7818-4472-9012-91c51fb0857d",
            "sourceColumn": "Região",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "81768dfb-e8ec-454c-92d4-7760900bb6eb",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Sigla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "d17c5371-011a-484f-a7e6-d9ad23a75edb",
            "sourceColumn": "Sigla",
            "summarizeBy": "none"
          },
          {
            "name": "Necessario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ad7a86a5-0e79-463f-8352-3f86e4da8c96",
            "sourceColumn": "Necessario",
            "summarizeBy": "sum"
          },
          {
            "name": "Minimo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6531f8f7-5ec1-428d-a255-9781d4d1c012",
            "sourceColumn": "Minimo",
            "summarizeBy": "sum"
          },
          {
            "name": "Pais",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Place",
            "dataType": "string",
            "lineageTag": "0091a4b3-4f30-487c-bddb-636025b7414a",
            "sourceColumn": "Pais",
            "summarizeBy": "none"
          },
          {
            "name": "Base64",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "9a75db89-8699-4a9d-a367-7549c5a54ae7",
            "sourceColumn": "Base64",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "2d7b0f2a-581d-4dfd-a91f-ded24d32d47a",
        "partitions": [
          {
            "name": "Dim_Estados",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Parametros,",
                "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each ([Item] = \"Estados\")),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Linhas Filtradas\",{\"Data\"}),",
                "    #\"Data Expandido\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas\", \"Data\", {\"Região\", \"Nome\", \"Sigla\"}, {\"Região\", \"Nome\", \"Sigla\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Data Expandido\",{{\"Região\", type text}, {\"Nome\", type text}, {\"Sigla\", type text}}),",
                "    Fonte2 = Table.NestedJoin(Estados, {\"Sigla\"}, ApoiamentosMínimos, {\"UF\"}, \"ApoiamentosMínimos\", JoinKind.LeftOuter),",
                "    #\"ApoiamentosMínimos Expandido\" = Table.ExpandTableColumn(Fonte2, \"ApoiamentosMínimos\", {\"0,5% DOS VOTOS VALIDOS\", \"0,1% DO ELEITORADO QUE VOTOU\"}, {\"0,5% DOS VOTOS VALIDOS\", \"0,1% DO ELEITORADO QUE VOTOU\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"ApoiamentosMínimos Expandido\",{{\"0,5% DOS VOTOS VALIDOS\", \"Necessario\"}, {\"0,1% DO ELEITORADO QUE VOTOU\", \"Minimo\"}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Pais\", each \"Brasil, \"&[Nome]),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Personalização Adicionada\", {\"Sigla\"}, Bandeiras, {\"Name\"}, \"Bandeiras\", JoinKind.LeftOuter),",
                "    #\"Bandeiras Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"Bandeiras\", {\"Base64\"}, {\"Base64\"})",
                "in",
                "    #\"Bandeiras Expandido\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fato_Apoiamentos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c599dd9a-9f57-4c70-896e-acc5c3663fcd",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "cac96120-1ce5-4c7e-9d70-d8dcbbaf28b5",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ff0e932-aede-4f6a-ae8e-c9c30cccf7d5",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          },
          {
            "name": "Apoiamentos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ab4172e6-cbea-4e1f-ba33-4d61df698c4c",
            "sourceColumn": "Apoiamentos",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5e25cacd-e9ad-4537-b216-eb9f9435ee75",
        "partitions": [
          {
            "name": "Fato_Apoiamentos",
            "mode": "import",
            "queryGroup": "Fatos",
            "source": {
              "expression": [
                "let",
                "    Fonte = Arquivos,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Arquivos,{\"Content\"}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Outras Colunas Removidas\", \"Dados\", each Csv.Document([Content], [Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None])),",
                "    #\"Dados Expandido\" = Table.ExpandTableColumn(#\"Personalização Adicionada\", \"Dados\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Dados Expandido\",{\"Column1\", \"Column2\", \"Column3\", \"Column4\"}),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Outras Colunas Removidas1\", [PromoteAllScalars=true]),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Cabeçalhos Promovidos\", each not Text.Contains([Data], \"Data\")),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Linhas Filtradas1\",{{\"Data\", type date}, {\"Estado\", type text}, {\"Apoiamentos\", type text}, {\"Nome\", type text}}),",
                "    #\"Texto Extraído Antes do Delimitador\" = Table.TransformColumns(#\"Tipo Alterado\", {{\"Nome\", each Text.BeforeDelimiter(_, \" - \"), type text}}),",
                "    #\"Intervalo de Texto Extraído\" = Table.TransformColumns(#\"Texto Extraído Antes do Delimitador\", {{\"Apoiamentos\", each Text.Middle(_, 16, 20), type text}}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Intervalo de Texto Extraído\",{{\"Apoiamentos\", type number}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Calendario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "c60ef898-f812-4975-85fc-5f8e5ae3d859",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d7ea513d-6f5a-48e2-a1ec-81a74f5e3b5b",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "237b20ad-0101-494f-83f5-c7474f59c758",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Nome do Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ab999cd-ce66-4180-b930-385e8164789b",
            "sourceColumn": "Nome do Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Ano/Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e00d6b70-e296-4455-8e78-e983a48b8545",
            "sourceColumn": "Ano/Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Numero Ano/Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "445b7a42-b6b1-4d97-9817-3dd2b2a1fcac",
            "sourceColumn": "Numero Ano/Mes",
            "summarizeBy": "sum"
          },
          {
            "name": "Semana do Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4dcc66cb-20c6-4c62-b160-214f933a8e9e",
            "sourceColumn": "Semana do Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Útil",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "655383ba-6670-40a7-9e99-1b465c2495fa",
            "sourceColumn": "Útil",
            "summarizeBy": "none"
          },
          {
            "name": "Ultima Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "VAR Ult = ",
              "CALCULATE(",
              "\tMAX(Fato_Apoiamentos[Data]),",
              "\tALL(Fato_Apoiamentos)",
              ")",
              "",
              "VAR Corrente = [Data]",
              "",
              "RETURN IF(Corrente = Ult, \"Atual\", \"Não\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "603cd3f2-4573-42cb-bf6d-5509430b5f4f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Data com Atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "VAR Ult = ",
              "CALCULATE(",
              "\tMAX(Fato_Apoiamentos[Data]),",
              "\tALL(Fato_Apoiamentos)",
              ")",
              "",
              "VAR Corrente = [Data]",
              "",
              "RETURN IF(Corrente = Ult, \"Atual\", FORMAT([Data], \"dd/mm/yyyy\"))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "09ac9d22-62d1-4578-aa21-68cdbe2284d9",
            "sortByColumn": "Data",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "9aea7f4f-9ad7-462a-a4b2-0e2b126f2dee",
        "partitions": [
          {
            "name": "Dim_Calendario",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    DataInicial = #date(2024,1,1),",
                "    DataFinal = #date(2026,12,31),",
                "    Duracao = Duration.Days(DataFinal - DataInicial) + 1,",
                "    Lista = List.Dates(DataInicial, Duracao, #duration(1, 0, 0, 0)),",
                "    #\"Convertido para Tabela\" = Table.FromList(Lista, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Convertido para Tabela\",{{\"Column1\", \"Data\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"Data\", type date}}),",
                "    #\"Ano Inserido\" = Table.AddColumn(#\"Tipo Alterado\", \"Ano\", each Date.Year([Data]), Int64.Type),",
                "    #\"Mês Inserido\" = Table.AddColumn(#\"Ano Inserido\", \"Mês\", each Date.Month([Data]), Int64.Type),",
                "    #\"Nome do Mês Inserido\" = Table.AddColumn(#\"Mês Inserido\", \"Nome do Mês\", each Date.MonthName([Data]), type text),",
                "    #\"Nome do Mês Inserido1\" = Table.AddColumn(#\"Nome do Mês Inserido\", \"Ano/Mês\", each Date.MonthName([Data]) & \"/\" & Text.From(Date.Year([Data])-2000), type text),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Nome do Mês Inserido1\", \"Numero Ano/Mes\", each (Date.Year([Data]) * 100) + Date.Month([Data])),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Numero Ano/Mes\", Int64.Type}}),",
                "    #\"Semana do Ano Inserida\" = Table.AddColumn(#\"Tipo Alterado1\", \"Semana do Ano\", each ([Ano] * 100) +  Date.WeekOfYear([Data]), Int64.Type),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Semana do Ano Inserida\", {\"Data\"}, DiasNaoUteis, {\"Datas\"}, \"DiasNaoUteis\", JoinKind.LeftOuter),",
                "    #\"DiasNaoUteis Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"DiasNaoUteis\", {\"Útil\"}, {\"Útil\"}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"DiasNaoUteis Expandido\",null,\"Sim\",Replacer.ReplaceValue,{\"Útil\"})",
                "in",
                "    #\"Valor Substituído\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "@Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "-",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65f58250-a0bb-4b79-a0ed-e9185ac0c927",
            "sourceColumn": "-",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "ac2ecc59-48a8-49aa-87fd-87fc53a95065",
        "measures": [
          {
            "name": "Total apoiamentos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR CALCULO = SUM(Fato_Apoiamentos[Apoiamentos])",
              "",
              "RETURN IF(CALCULO = 0, BLANK(), CALCULO)"
            ],
            "formatString": "#,0",
            "lineageTag": "0a6517a3-62ee-401f-a287-731b0ba7a08f"
          },
          {
            "name": "Apoiamento mínimo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(Dim_Estados[Minimo])",
            "formatString": "#,0",
            "lineageTag": "7323f435-404f-4f90-8972-0024078da05b"
          },
          {
            "name": "Apoiamentos necessários",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "ROUNDUP(",
              "CALCULATE(",
              "\tSUM(Dim_Estados[Necessario]),",
              "\tALL(Dim_Estados[Necessario])",
              "),0)"
            ],
            "formatString": "#,0",
            "lineageTag": "37168a0c-e8ed-4ee3-9368-90478375b858"
          },
          {
            "name": "Apoiamentos acima do mínimo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR APOIAMENTOS = [Total apoiamentos]",
              "",
              "VAR TOTAL = IF(APOIAMENTOS >= [Apoiamentos necessários], APOIAMENTOS, BLANK())",
              "",
              "VAR CALCULO = ",
              "",
              "SUMX(",
              "\tVALUES(Dim_Estados),",
              "\tVAR Apoio = [Total apoiamentos]",
              "\tVAR Minimo = [Apoiamentos mín]",
              "\tVAR Calculo = IF(Apoio >= Minimo, Apoio, 0)",
              "\tRETURN IF(Calculo = 0, BLANK(), Calculo)",
              ")",
              "",
              "VAR CONDICAO = IF(ISINSCOPE(Dim_Estados[Nome]) || ISINSCOPE(Dim_Estados[Sigla]), CALCULO, TOTAL)",
              "",
              "RETURN CONDICAO"
            ],
            "formatString": "#,0",
            "lineageTag": "569806e1-e4b2-4512-ae97-5e1ecc032108"
          },
          {
            "name": "Apoiamentos abaixo do mínimo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "SUMX(",
              "\tVALUES(Dim_Estados),",
              "\tVAR Apoio = [Total apoiamentos]",
              "\tVAR Minimo = ROUNDUP( [Apoiamento mínimo],0)",
              "\tVAR Calculo = IF(Apoio < Minimo, Apoio, 0)",
              "\tRETURN IF(Calculo = 0, BLANK(), Calculo)",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "2696e526-e59a-4d8a-a5c0-639764582a71"
          },
          {
            "name": "Mínimo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "SUMX(",
              "\tVALUES(Dim_Estados),",
              "\tIF([Total apoiamentos] > 0, [Apoiamento mínimo], BLANK())",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "c6afe0ab-0a6d-4f6c-904e-e682b9e1b322"
          },
          {
            "name": "Última validação",
            "expression": "MAX(Fato_Apoiamentos[Data])",
            "formatString": "Short Date",
            "lineageTag": "cef8e065-57b3-42bc-b123-ed9851ed2e5c"
          },
          {
            "name": "Data corte",
            "expression": "DATE(2024, 10, 31)",
            "formatString": "Short Date",
            "lineageTag": "ad10627e-85f6-4322-8ca7-c08e0f1b2e9c"
          },
          {
            "name": "Validações restantes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[Apoiamentos necessários] - [Total apoiamentos]",
            "formatString": "#,0",
            "lineageTag": "0d504bd9-7375-485a-9dd5-1508e994cff5"
          },
          {
            "name": "Dias úteis restantes antes de novembro de 2024",
            "expression": [
              "",
              "",
              "VAR Data_Corrente = MAX(Dim_Calendario[Data])",
              "",
              "RETURN",
              "",
              "COUNTROWS(",
              "\tFILTER(",
              "\t\tALL(Dim_Calendario),",
              "\t\t[Data] > Data_Corrente &&",
              "\t\t[Data] <= [Data corte] &&",
              "\t\t[Útil] = \"Sim\"",
              "\t)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "960d8b36-1264-4727-a685-596e167ceb51"
          },
          {
            "name": "Dias úteis restantes até o prazo final no TSE",
            "expression": [
              "",
              "",
              "VAR Data_Corrente = MAX(Dim_Calendario[Data])",
              "",
              "RETURN",
              "",
              "COUNTROWS(",
              "\tFILTER(",
              "\t\tALL(Dim_Calendario),",
              "\t\t[Data] > Data_Corrente &&",
              "\t\t[Data] <= DATE(2025, 11, 22) &&",
              "\t\t[Útil] = \"Sim\"",
              "\t)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4a710de0-a6cc-462d-887f-cafc43c36cc1"
          },
          {
            "name": "Ranking geral",
            "expression": [
              "",
              "",
              "VAR Tabela = ",
              "",
              "FILTER(",
              "\tALL(Dim_Estados),",
              "\t[Total apoiamentos] > 0",
              ")",
              "",
              "VAR CALCULO = ",
              "",
              "RANKX(Tabela, [Total apoiamentos])",
              "",
              "RETURN IF(ISBLANK([Total apoiamentos]) || NOT(ISCROSSFILTERED(Dim_Estados)), BLANK(), CALCULO)"
            ],
            "formatString": "0",
            "lineageTag": "9583bec9-af7d-4c7a-84d4-199bc349299c"
          },
          {
            "name": "Validações diárias necessárias antes de novembro de 2024",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR Media = ",
              "",
              "DIVIDE([Validações restantes], [Dias úteis restantes antes de novembro de 2024])",
              "",
              "RETURN IF(ISBLANK([Variação diária]), BLANK(), Media)"
            ],
            "formatString": "#,0",
            "lineageTag": "5880d113-6bd0-4582-ba82-d480398e0db6"
          },
          {
            "name": "Validações diárias necessárias até o prazo final no TSE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "VAR Media = ",
              "",
              "DIVIDE([Validações restantes], [Dias úteis restantes até o prazo final no TSE])",
              "",
              "RETURN IF(ISBLANK([Variação diária]), BLANK(), Media)"
            ],
            "formatString": "#,0",
            "lineageTag": "32d18662-d9fa-46e5-9f57-c78fb5cd3fd2"
          },
          {
            "name": "Número de estados que precisam coletar o mínimo",
            "expression": "9",
            "formatString": "0",
            "lineageTag": "6f381d22-8af0-4114-a4db-dd1413dd2ca7"
          },
          {
            "name": "Estados que já cumpriram o mínimo",
            "expression": [
              "",
              "",
              "COUNTROWS(",
              "\tFILTER(",
              "\t\tVALUES(Dim_Estados),",
              "\t\t[Apoiamentos acima do mínimo] > 0",
              "\t)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3a64fa62-5415-45dc-ba84-7ffd75c102c4"
          },
          {
            "name": "Apoiamentos mín",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR APOIOS = [Total apoiamentos]",
              "VAR MINIMO = [Apoiamento mínimo]",
              "VAR NECESSARIO = [Apoiamentos necessários]",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(APOIOS), BLANK(),",
              "    NOT(ISINSCOPE(Dim_Estados[Nome])), NECESSARIO,",
              "    MINIMO",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "28829d2a-d716-4541-93ae-5ad4a88afe3a"
          },
          {
            "name": "Formatação acima do mínimo",
            "expression": [
              "",
              "",
              "VAR VALOR = [Apoiamentos acima do mínimo]",
              "",
              "VAR CALCULO = IF(ISCROSSFILTERED(Dim_Estados), VALOR ,BLANK())",
              "",
              "RETURN IF(ISBLANK(VALOR) || ISBLANK([Total apoiamentos]), BLANK(), 1)"
            ],
            "formatString": "0",
            "lineageTag": "9e7f01c6-3c45-40e3-9032-1cef07aa9b94"
          },
          {
            "name": "Variação diária",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "VAR Dia_Atual = [Total apoiamentos]",
              "",
              "VAR Data_Anterior = LASTDATE(Fato_Apoiamentos[Data]) -1",
              "",
              "VAR Dia_Anterior = ",
              "",
              "CALCULATE(",
              "\t[Total apoiamentos],",
              "\tDim_Calendario[Data] = Data_Anterior",
              ")",
              "",
              "",
              "VAR CALCULO = ",
              "",
              "Dia_Atual - Dia_Anterior",
              "",
              "RETURN CALCULO"
            ],
            "formatString": "#,0",
            "lineageTag": "45c89ead-65e4-416c-94f9-73d0ed57348b"
          },
          {
            "name": "% Validado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Total apoiamentos], [Apoiamentos necessários])",
            "lineageTag": "c486afa4-215f-482b-a4a6-34409ecd4f0d"
          },
          {
            "name": "% Restante",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Validações restantes], [Apoiamentos necessários])",
            "lineageTag": "85f7a6d5-df73-47bc-ba00-2a95cca81503"
          },
          {
            "name": "Total apoiamentos2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR CALCULO = SUM(Fato_Apoiamentos[Apoiamentos])",
              "",
              "VAR CALCULO2 = ",
              "",
              "CALCULATE(",
              "    SUM(Fato_Apoiamentos[Apoiamentos]),",
              "    ALL(Fato_Apoiamentos[Nome])",
              ")",
              "",
              "VAR CONDICAO = ISBLANK(CALCULO2) || CALCULO2 = 0",
              "",
              "RETURN  ",
              "",
              "--IF(CONDICAO, BLANK(), CALCULO)",
              "",
              "CALCULO"
            ],
            "formatString": "#,0",
            "lineageTag": "dc23af67-794e-49ba-9999-7ad675d07a44"
          },
          {
            "name": "Título Resumo",
            "expression": [
              "\"Resumo Validações de Apoiamentos no TSE - \" & [DataHoraAtualização]",
              "\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
              ""
            ],
            "lineageTag": "20eae0f8-9da4-4584-b98e-9c34eaaa981e"
          },
          {
            "name": "Título Comparação",
            "expression": "\"Comparação das Validações no TSE - Partidos em Formação - \" & [DataHoraAtualização]",
            "lineageTag": "9e0243b7-1cd4-43eb-8145-a2dbfd9cde4b"
          },
          {
            "name": "DataHoraAtualização",
            "expression": "MAX('Atualização'[Atualização]) - TIME(3,0,0)",
            "formatString": "General Date",
            "lineageTag": "7379213b-655b-4429-8a82-28078bc79783"
          },
          {
            "name": "Restante minimo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR APOIOS = [Total apoiamentos]",
              "VAR MINIMO = [Apoiamento mínimo]",
              "VAR NECESSARIO = [Apoiamentos necessários]",
              "",
              "RETURN",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(APOIOS), BLANK(),",
              "    NOT(ISINSCOPE(Dim_Estados[Nome])), NECESSARIO - APOIOS,",
              "    MAX( MINIMO - APOIOS, 0 )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "26b641ac-91f6-49e2-a42f-939f76893001"
          },
          {
            "name": "% do minimo",
            "expression": [
              "",
              "",
              "VAR PERCENTUAL = DIVIDE( [Total apoiamentos],  [Apoiamentos mín]  )",
              "",
              "VAR CALCULO = MIN( PERCENTUAL, 1)",
              "",
              "VAR CALCULO2 = IF(CALCULO < 1, MIN(CALCULO, 0.9999), CALCULO)",
              "",
              "RETURN",
              "",
              "IF(",
              "    ISBLANK( [Total apoiamentos] ), ",
              "    BLANK(), ",
              "    CALCULO2",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "06d65b4a-5332-4e48-af12-434efc072439"
          },
          {
            "name": "Projeção",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "IF(SELECTEDVALUE(Dim_Calendario[Data]) > [Expectativa de conclusão], BLANK(), [ProjeçãoBase])"
            ],
            "formatString": "#,0",
            "lineageTag": "684713eb-1911-43f8-b3d7-c1eb7975b2f9"
          },
          {
            "name": "Média diária úlimos 7 dias",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR Ultima = [Última validação]",
              "",
              "VAR Anterior = [Última validação] - 1",
              "",
              "VAR Primeira_Data = ",
              "",
              "MINX(",
              "    TOPN(",
              "        7,",
              "        FILTER(",
              "            ALL(Dim_Calendario),",
              "            [Variação diária] > 0 &&",
              "            [Data] < Ultima  &&",
              "            [Útil] = \"Sim\"",
              "        ),",
              "        [Data],",
              "        DESC",
              "    ),",
              "    [Data]",
              ") - 1",
              "",
              "VAR Valor_Anterior = ",
              "",
              "CALCULATE(",
              "    [Total apoiamentos],",
              "    Dim_Calendario[Data] = Primeira_Data",
              ")",
              "",
              "VAR Valor_Recente = ",
              "",
              "CALCULATE(",
              "    [Total apoiamentos],",
              "    Dim_Calendario[Data] = Anterior",
              ")",
              "",
              "VAR Calculo = DIVIDE( Valor_Recente - Valor_Anterior , 7 )",
              "",
              "RETURN Calculo",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "7fbda250-cc51-4e81-85f9-749ffab9635d"
          },
          {
            "name": "Título Projeção",
            "expression": "\"Projeção das Validações Futuras - \" & [DataHoraAtualização]",
            "lineageTag": "fb84211f-0289-4b2c-ae13-8200b1c1fb67"
          },
          {
            "name": "Expectativa de conclusão",
            "expression": [
              "",
              "",
              "MINX(",
              "    FILTER(",
              "        ALL(Dim_Calendario[Data],Dim_Calendario[Útil]),",
              "        [Útil] = \"Sim\"&&",
              "        [ProjeçãoBase] >= [Apoiamentos necessários]",
              "    ),",
              "    Dim_Calendario[Data]",
              ")"
            ],
            "formatString": "Short Date",
            "lineageTag": "5743beb6-3885-4161-b1e4-86597569a4e1"
          },
          {
            "name": "Título Mapa",
            "expression": "\"Mapa dos Apoiamentos no TSE por Estado - \" & [DataHoraAtualização]",
            "lineageTag": "9b520ce5-ba8d-45fb-a11e-7f0f16c7c7cf"
          },
          {
            "name": "Validados Alianca",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM('Coleta Aliança'[Rateio])",
            "formatString": "#,0",
            "lineageTag": "f1559f9b-87d7-4685-a615-0fbfa66abcb6"
          },
          {
            "name": "Total Validado Aliança",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "LASTNONBLANKVALUE(",
              "    ALL(Dim_Calendario[Data]),",
              "    [Validados Alianca]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "e4b95acb-af3d-4efb-af55-16175c462f10"
          },
          {
            "name": "Badeira",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "",
              "IF(",
              "    ISBLANK([Total apoiamentos])",
              "    , BLANK(),",
              "    SELECTEDVALUE(Bandeiras[Base64])",
              ")"
            ],
            "lineageTag": "a2a06c06-ee58-4930-ae68-deff8e5e0277"
          },
          {
            "name": "Título Principal",
            "expression": [
              "\"Validações de Apoiamentos no TSE - \" & [DataHoraAtualização]",
              "\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
              ""
            ],
            "lineageTag": "b1748fc1-b4dd-4bfa-a668-bbceb7acca48"
          },
          {
            "name": "ProjeçãoBase",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR DATA_ATUAL = ",
              "",
              "CALCULATE(",
              "    MAX(Dim_Calendario[Data]),",
              "    ALL(Dim_Calendario),",
              "    Dim_Calendario[Ultima Data] = \"Atual\"",
              ")",
              "",
              "VAR DATA_CONTEXTO = SELECTEDVALUE(Dim_Calendario[Data])",
              "",
              "VAR TAB_UTEIS = ",
              "",
              "FILTER(",
              "    ALL(Dim_Calendario),",
              "    [Data] >= DATA_ATUAL&&",
              "    Dim_Calendario[Útil] = \"Sim\"&&",
              "    [Data] <= DATA_CONTEXTO",
              ")",
              "",
              "VAR ULTIMA_MEDIA_7_DIAS = ",
              "",
              "CALCULATE(",
              "    [Média diária úlimos 7 dias],",
              "    ALL(Dim_Calendario),",
              "    Dim_Calendario[Ultima Data] = \"Atual\"",
              ")",
              "",
              "VAR Realizado = ",
              "",
              "LASTNONBLANKVALUE(",
              "    CALCULATETABLE(",
              "        VALUES(Dim_Calendario[Data]),",
              "        ALL(Dim_Calendario),",
              "        Dim_Calendario[Data] < DATA_ATUAL,",
              "        Dim_Calendario[Útil] = \"Sim\"",
              "    ),",
              "    [Total apoiamentos]",
              ")",
              "",
              "VAR QTD_DIAS_UTEIS = COUNTROWS(TAB_UTEIS)",
              "",
              "VAR CALCULO = ",
              "",
              "Realizado + (QTD_DIAS_UTEIS * ULTIMA_MEDIA_7_DIAS)",
              "",
              "VAR TESTE = ",
              "",
              "IF(DATA_CONTEXTO <= DATA_ATUAL, BLANK(), CALCULO)",
              "",
              "RETURN TESTE"
            ],
            "lineageTag": "929dbbc9-9099-44bd-9dde-f771581b6bd4"
          },
          {
            "name": "Prazo Máximo TSE",
            "expression": [
              "",
              " ",
              "DATE(2025, 11, 22)"
            ],
            "formatString": "Short Date",
            "lineageTag": "59032e10-ed7e-4048-a43e-0f58b8542887"
          },
          {
            "name": "Data Congresso",
            "expression": "DATE(2024, 11, 23)",
            "formatString": "General Date",
            "lineageTag": "33311d7d-bdf9-402e-ae6a-2422207d83dc"
          },
          {
            "name": "Projeção Data Congresso",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR DATA = [Data Congresso]",
              "",
              "RETURN",
              "",
              "CALCULATE(",
              "    [ProjeçãoBase],",
              "    Dim_Calendario[Data] = DATA",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "99dfbf30-9615-43f0-af20-05fd1a5f5e4c"
          },
          {
            "name": "Último recorde diário",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR ULTIMA = [Última validação]",
              "",
              "VAR CALCULO = ",
              "",
              "MAXX(",
              "    FILTER(",
              "        ALL(Dim_Calendario),",
              "        [Variação diária] > 0 &&",
              "        [Data] < ULTIMA  &&",
              "        [Data] > DATE(2024, 4, 27)",
              "    ),",
              "    [Variação diária]",
              ")",
              "",
              "RETURN CALCULO"
            ],
            "formatString": "#,0",
            "lineageTag": "0934b6d4-a8b7-443c-b2ec-bb99142e5d64"
          },
          {
            "name": "Data do último recorde",
            "expression": [
              "",
              "",
              "VAR ULTIMO_RECORDE = [Último recorde diário]",
              "",
              "VAR CALCULO = ",
              "",
              "MINX(",
              "    FILTER(",
              "        ALL(Dim_Calendario),",
              "        [Variação diária] = ULTIMO_RECORDE &&",
              "        [Útil] = \"Sim\"",
              "    ),",
              "    [Data]",
              ")",
              "",
              "RETURN CALCULO"
            ],
            "formatString": "Short Date",
            "lineageTag": "ccb1678d-1571-444e-a195-cfd34ff40543"
          },
          {
            "name": "Última data listagem",
            "expression": [
              "",
              "",
              "LASTNONBLANK(",
              "    ALL(Dim_Calendario[Data]),",
              "    CALCULATE(SUM(Fato_Apoiamentos[Apoiamentos]))",
              ")"
            ],
            "formatString": "Short Date",
            "lineageTag": "30732103-0a30-46b9-b719-35cd67242296"
          }
        ],
        "partitions": [
          {
            "name": "@Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = \"-\",",
                "    #\"Convertido para Tabela\" = #table(1, {{Fonte}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Convertido para Tabela\",{{\"Column1\", \"-\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"-\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Atualização",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "DateTimeZone"
          }
        ],
        "columns": [
          {
            "name": "Atualização",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ac7842dc-69ef-49de-857d-d0542046dca9",
            "sourceColumn": "Atualização",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "daf817b5-863a-41d9-8649-c0917bc6012a",
        "partitions": [
          {
            "name": "Atualização",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Arquivos,",
                "    UltimaAtualizacao = List.Max( Fonte[Date modified] )",
                "in",
                "    UltimaAtualizacao"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Coleta Aliança",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Data convetida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c64a8fbd-3329-47c7-9e23-75bd3ab6eec4",
            "sourceColumn": "Data convetida",
            "summarizeBy": "none"
          },
          {
            "name": "Rateio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b2db53a6-072b-4f49-b653-b9e0298ec664",
            "sourceColumn": "Rateio",
            "summarizeBy": "sum"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "27b01061-5e66-4797-8112-3dfa256d946c",
        "partitions": [
          {
            "name": "Coleta Aliança",
            "mode": "import",
            "queryGroup": "Fatos",
            "source": {
              "expression": [
                "let",
                "    Fonte = Parametros,",
                "    Data = Fonte{0}[Data]",
                "in",
                "    Data"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Bandeiras",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "126df89a-6ba7-486e-bf7b-e396a9a25ae9",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Base64",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "8872510b-7931-40b9-8508-6ceb2fe44055",
            "sourceColumn": "Base64",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "7aab7592-e7b1-477d-8000-8e8cfcbeb543",
        "partitions": [
          {
            "name": "Bandeiras",
            "mode": "import",
            "queryGroup": "Parametros",
            "source": {
              "expression": [
                "let",
                "    Fonte = ParametrosBase,",
                "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each ([Name] = \"Bandeiras dos Estados\")),",
                "    #\"Bandeiras dos Estados\" = #\"Linhas Filtradas\"{[Name=\"Bandeiras dos Estados\"]}[Content],",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Bandeiras dos Estados\",{\"Content\", \"Name\", \"Extension\"}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Outras Colunas Removidas\", \"Base64\", each \"data:image/png;base64,\" & Binary.ToText([Content])),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Base64\", type text}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado\",\".png\",\"\",Replacer.ReplaceText,{\"Name\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Valor Substituído\",{\"Name\", \"Base64\"})",
                "in",
                "    #\"Outras Colunas Removidas1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ResumoExportao",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f98e8ce62d3b4642a8ebe24480d43106"
          }
        ],
        "columns": [
          {
            "name": "11 - Total_apoiamentos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a915066a-56f5-4f0b-8abd-9651e6974c59",
            "sourceColumn": "[11 - Total_apoiamentos]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "12 - Apoiamentos_necessarios",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "59b868f1-5a81-4d93-9e27-fbdbcdc59321",
            "sourceColumn": "[12 - Apoiamentos_necessarios]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "13 - Validacoes_restantes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "81ac4e7b-e8ee-4e53-a591-f688c5d4cd1c",
            "sourceColumn": "[13 - Validacoes_restantes]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "14 - Dias_uteis_restantes_ate_o_prazo_final_no_TSE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "234f84b7-8eb0-42df-a469-7bde260258b7",
            "sourceColumn": "[14 - Dias_uteis_restantes_ate_o_prazo_final_no_TSE]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "15 - Numero_de_estados_que_precisam_coletar_o_minimo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "15f6ef78-1704-44da-8a0a-8af2f236a5b2",
            "sourceColumn": "[15 - Numero_de_estados_que_precisam_coletar_o_minimo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "16 - Estados_que_ja_cumpriram_o_minimo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a7808067-3426-4627-8ad9-df1341418ff5",
            "sourceColumn": "[16 - Estados_que_ja_cumpriram_o_minimo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "17 - Expectativa_de_conclusao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b4e0f27d-968d-4c8c-b55a-0645f487d919",
            "sourceColumn": "[17 - Expectativa_de_conclusao]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "18 - DataHoraAtualizacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c13a6a68-67f5-400a-ae47-920f06250725",
            "sourceColumn": "[18 - DataHoraAtualizacao]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "19 - Validações_diarias_necessarias_ate_o_prazo_final_no_TSE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0c13617e-ede0-49c2-b42e-544cfa100cc0",
            "sourceColumn": "[19 - Validações_diarias_necessarias_ate_o_prazo_final_no_TSE]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "20 - Média diária úlimos 7 dias",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "69656b4b-65f9-47dc-9317-69d18d469805",
            "sourceColumn": "[20 - Média diária úlimos 7 dias]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "21 - Ultimo recorde diário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "254bd6b2-d05e-4505-9e59-942152f75f65",
            "sourceColumn": "[21 - Ultimo recorde diário]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "22 - Variacao diaria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cd4de7f3-fea1-4f1d-85c5-b380ae346c48",
            "sourceColumn": "[22 - Variacao diaria]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "80c3acdf-0752-446f-9069-61decea395fa",
        "partitions": [
          {
            "name": "ResumoExportao",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "",
                "\tVAR __DS0FilterTable = ",
                "\t\tTREATAS({\"Atual\"}, 'Dim_Calendario'[Data com Atual])",
                "",
                "\tVAR __DS0FilterTable2 = ",
                "\t\tTREATAS({\"MISSÃO\"}, 'Fato_Apoiamentos'[Nome])",
                "",
                "\tVAR __DS0FilterTable3 = ",
                "\t\tFILTER(",
                "\t\t\tKEEPFILTERS(VALUES('Dim_Calendario'[Data])),",
                "\t\t\tAND(",
                "\t\t\t\t'Dim_Calendario'[Data] >= DATE(2024, 5, 21),",
                "\t\t\t\tNOT(ISBLANK('Dim_Calendario'[Data]))",
                "\t\t\t)",
                "\t\t)",
                "",
                "RETURN",
                "\tSUMMARIZECOLUMNS(",
                "\t\t__DS0FilterTable,",
                "\t\t__DS0FilterTable2,",
                "\t\t__DS0FilterTable3,",
                "\t\t\"11 - Total_apoiamentos\", '@Medidas'[Total apoiamentos],",
                "\t\t\"12 - Apoiamentos_necessarios\", '@Medidas'[Apoiamentos necessários],",
                "\t\t\"13 - Validacoes_restantes\", '@Medidas'[Validações restantes],",
                "\t\t\"14 - Dias_uteis_restantes_ate_o_prazo_final_no_TSE\", '@Medidas'[Dias úteis restantes até o prazo final no TSE],",
                "\t\t\"15 - Numero_de_estados_que_precisam_coletar_o_minimo\", '@Medidas'[Número de estados que precisam coletar o mínimo],",
                "\t\t\"16 - Estados_que_ja_cumpriram_o_minimo\", '@Medidas'[Estados que já cumpriram o mínimo],",
                "\t\t\"17 - Expectativa_de_conclusao\", '@Medidas'[Expectativa de conclusão],",
                "\t\t\"18 - DataHoraAtualizacao\", '@Medidas'[DataHoraAtualização],",
                "\t\t\"19 - Validações_diarias_necessarias_ate_o_prazo_final_no_TSE\", ROUND('@Medidas'[Validações diárias necessárias até o prazo final no TSE],0),",
                "\t\t\"20 - Média diária úlimos 7 dias\", '@Medidas'[Média diária úlimos 7 dias],",
                "        \"21 - Ultimo recorde diário\", '@Medidas'[Último recorde diário],",
                "        \"22 - Variacao diaria\", '@Medidas'[Variação diária]",
                "\t)"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}